import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {root,load} from './content.mjs';
import {build} from './build.mjs';
import {startServer} from './serve.mjs';
import {browser,pause} from './audit/cdp.mjs';
const dir=path.join(root,'artifacts/apple-like');await fs.mkdir(dir,{recursive:true});
const d=await load(),results=[],widths=[320,390,480,768,1024,1440,1920];let chrome;const servers=[];
async function check(name,run){try{const value=await run();results.push({name,status:'PASS',value});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message);}}
async function capture(name){const r=await chrome.call('Page.captureScreenshot',{format:'jpeg',quality:60,captureBeyondViewport:false});await fs.writeFile(path.join(dir,name+'.jpg'),Buffer.from(r.data,'base64'));}
async function media(){await chrome.evaluate(`(async()=>{const y=scrollY;for(const im of [...document.querySelectorAll('main img')].filter(x=>x.checkVisibility())){im.scrollIntoView({behavior:'instant'});await new Promise(r=>setTimeout(r,30));await Promise.race([im.decode(),new Promise((_,reject)=>setTimeout(()=>reject(Error('Image decode timed out')),3500))]);}scrollTo({top:y,behavior:'instant'});})()`);}
try{
 await build();await build({domain:true});const s=await startServer(path.join(root,'dist')),t=await startServer(path.join(root,'dist-domain'),'/');servers.push(s.server,t.server);chrome=await browser();
 for(const l of ['en','pt-BR'])for(const width of widths)await check('layout '+l+' '+width,async()=>{
  await chrome.go(s.url+(l==='en'?'':'pt-br/'),width,900);await media();
  const m=await chrome.evaluate(`(()=>{const visible=x=>x.checkVisibility()&&x.getBoundingClientRect().width>0&&x.getBoundingClientRect().height>0;const buttons=[...document.querySelectorAll('button,summary,nav a,.button,.text-link')].filter(visible);let drift=0;for(const g of document.querySelectorAll('.grid')){const r=g.getBoundingClientRect(),cs=getComputedStyle(g),cols=cs.gridTemplateColumns.split(' ').map(parseFloat),gap=parseFloat(cs.columnGap);const starts=[],ends=[];let x=r.left;for(const w of cols){starts.push(x);ends.push(x+w);x+=w+gap;}for(const el of g.children){const b=el.getBoundingClientRect();drift=Math.max(drift,Math.min(...starts.map(x=>Math.abs(x-b.left))),Math.min(...ends.map(x=>Math.abs(x-b.right))));}}return {overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),h1:document.querySelectorAll('h1').length,language:document.documentElement.lang,small:buttons.filter(x=>x.getBoundingClientRect().height<43||x.getBoundingClientRect().width<43).map(x=>x.textContent.slice(0,40)),badImages:[...document.querySelectorAll('main img')].filter(visible).filter(x=>!x.complete||!x.naturalWidth||!x.alt).length,drift,body:getComputedStyle(document.body).backgroundColor,font:getComputedStyle(document.querySelector('h1')).fontFamily,archivo:document.fonts.check('800 80px Archivo'),inter:document.fonts.check('400 16px Inter'),iframe:document.querySelectorAll('iframe').length};})()`);
  assert.equal(m.overflow,0);assert.equal(m.h1,1);assert.equal(m.language,l);assert.deepEqual(m.small,[]);assert.equal(m.badImages,0);assert.ok(m.drift<=1);assert.equal(m.body,'rgb(5, 5, 5)');assert.match(m.font,/Archivo/);assert.ok(m.archivo&&m.inter);assert.equal(m.iframe,0);
  if([390,1440].includes(width)){await chrome.evaluate('scrollTo({top:0,behavior:"instant"})');await capture('hero-'+l+'-'+width);await chrome.evaluate('document.querySelector("#music").scrollIntoView({behavior:"instant"})');await capture('music-'+l+'-'+width);}return m;
 });
 for(const l of ['en','pt-BR']){
  await chrome.go(s.url+(l==='en'?'':'pt-br/'),l==='en'?1440:390,900);await chrome.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  for(const r of d.releases)await check('release '+l+' '+r.id,async()=>{await chrome.evaluate(`document.querySelector('[data-release="${r.id}"]').click()`);await pause(50);assert.equal(await chrome.evaluate('document.querySelector("#release-viewer").open'),true);const value=await chrome.evaluate('document.querySelector("#release-viewer .release-title").textContent');assert.equal(value,r.title);assert.ok(await chrome.evaluate('document.querySelector("#release-viewer").scrollWidth-document.querySelector("#release-viewer").clientWidth<=1'));await chrome.evaluate('document.querySelector("[data-close]").click()');await pause(70);assert.equal(await chrome.evaluate('document.querySelector("#release-viewer").open'),false);});
 }
 await check('dialog keyboard, Escape, focus, Back and Forward',async()=>{
  await chrome.go(s.url,1440,900);await chrome.evaluate('document.querySelector("[data-release]").click()');await pause(100);
  for(let i=0;i<18;i++){await chrome.call('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await chrome.call('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});assert.ok(await chrome.evaluate('!!document.activeElement.closest("dialog[open]")'));}
  await capture('release-desktop');await chrome.call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await pause(100);assert.equal(await chrome.evaluate('!!document.querySelector("dialog[open]")'),false);assert.ok(await chrome.evaluate('!!document.activeElement.dataset.release'));await chrome.evaluate('history.forward()');await pause(100);assert.equal(await chrome.evaluate('document.querySelector("#release-viewer").open'),true);await chrome.evaluate('history.back()');await pause(100);
 });
 await check('mobile drawer includes language, traps focus and closes',async()=>{
  await chrome.go(s.url+'pt-br/',390,844);await chrome.evaluate('document.querySelector("[data-menu-open]").click()');assert.equal(await chrome.evaluate('document.querySelector("#navigation").open'),true);assert.equal(await chrome.evaluate('document.querySelectorAll("#navigation .languages a").length'),2);await capture('drawer-pt');
  for(let i=0;i<12;i++){await chrome.call('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await chrome.call('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});assert.ok(await chrome.evaluate('!!document.activeElement.closest("#navigation")'));}
  await chrome.evaluate('document.querySelector("#navigation a[href$=\\"#music\\"]").click()');assert.equal(await chrome.evaluate('document.querySelector("#navigation").open'),false);assert.ok(await chrome.evaluate('location.hash==="#music"'));
 });
 await check('all videos consent gated with no autoplay',async()=>{await chrome.go(s.url,1440,900);await chrome.evaluate('document.querySelector(".video-more").open=true');await media();assert.equal(await chrome.evaluate('document.querySelectorAll("iframe").length'),0);for(const v of d.videos){await chrome.evaluate(`document.querySelector('[data-video="${v.id}"]').click()`);assert.ok(await chrome.evaluate(`!!document.querySelector('iframe[src="https://www.youtube-nocookie.com/embed/${v.id}"]')`));}assert.ok(await chrome.evaluate('[...document.querySelectorAll("iframe")].every(f=>f.referrerPolicy==="strict-origin-when-cross-origin"&&!f.src.includes("autoplay"))'));});
 await check('reduced motion eliminates decorative transitions',async()=>{await chrome.go(s.url,390,844);await chrome.evaluate('document.querySelector("[data-menu-open]").click()');assert.equal(await chrome.evaluate('getComputedStyle(document.querySelector("#navigation")).animationName'),'none');assert.equal(await chrome.evaluate('getComputedStyle(document.documentElement).scrollBehavior'),'auto');});
 await check('static release page and menu without JavaScript',async()=>{await chrome.call('Emulation.setScriptExecutionDisabled',{value:true});try{await chrome.go(s.url+'pt-br/releases/antes-de-tudo-2014/',390,844);assert.equal(await chrome.evaluate('document.querySelectorAll(".tracks li").length'),9);assert.ok(await chrome.evaluate('document.querySelector(".fallback-menu").getBoundingClientRect().height>0'));assert.ok(await chrome.evaluate('!!document.querySelector("a[href^=\\"https://open.spotify.com/album/\\"]")'));}finally{await chrome.call('Emulation.setScriptExecutionDisabled',{value:false});}});
 for(const l of ['en','pt-BR'])await check('custom-domain root routing '+l,async()=>{await chrome.go(t.url+(l==='en'?'':'pt-br/'),390,844);assert.equal(await chrome.evaluate('document.documentElement.lang'),l);assert.equal(await chrome.evaluate('document.querySelector("link[rel=canonical]").href'),'https://axl.sssom.com/'+(l==='en'?'':'pt-br/'));assert.ok(await chrome.evaluate('document.querySelector(".portrait img").complete&&document.querySelector(".portrait img").naturalWidth>0'));});
 const sourceFiles=['scripts/render.mjs','scripts/content.mjs','scripts/build.mjs','scripts/audit.mjs','site/assets/css/style.css','site/assets/js/app.js'];const hashes={};for(const file of sourceFiles)hashes[file]=createHash('sha256').update(await fs.readFile(path.join(root,file))).digest('hex');
 const report={date:new Date().toISOString(),browser:(await chrome.call('Browser.getVersion')).product,policy:'Original Apple-like / Müller audit, not Apple certification',results,failures:results.filter(r=>r.status==='FAIL').length,hashes,limits:['Human English review pending','Physical iOS/Android, assistive-technology and colour fidelity review not claimed','Video frame configuration tested, not third-party playback availability','External Google Fonts requests are intentional; no font binaries bundled','Custom domain tested locally, not public DNS/HTTPS']};
 await fs.writeFile(path.join(dir,'report.json'),JSON.stringify(report,null,2));console.log('APPLE_AUDIT',results.length,report.failures);if(report.failures)process.exitCode=1;
}finally{await chrome?.close();for(const s of servers){s.closeAllConnections();await new Promise(r=>s.close(r));}}
