import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {root,load,validate,hosting,locales,prefix,safePath} from './content.mjs';
import {render,route} from './render.mjs';
import {markdown,llms,structured} from './discovery.mjs';
export function generate(d,h){validate(d);const out=new Map();for(const l of locales){for(const r of [null,...d.releases]){out.set(route(l,r)+'index.html',render(d,l,h,{release:r}));out.set(route(l,r)+'index.md',markdown(d,l,h,r));}out.set(prefix(l)+'portfolio.json',JSON.stringify(structured(d,l,h),null,2)+'\n');}out.set('llms.txt',llms(d,h));out.set('llms-full.txt',locales.map(l=>[null,...d.releases].map(r=>markdown(d,l,h,r)).join('\n---\n')).join('\n---\n'));out.set('robots.txt','# Preview: noindex in HTML; this file is effective only at the origin root.\nUser-agent: *\nDisallow: '+h.base+'\n');out.set('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>\n');out.set('404.html',render(d,'en',h,{notFound:true}));out.set('.nojekyll','');if(h.origin==='https://axl.sssom.com'&&h.base==='/')out.set('CNAME','axl.sssom.com\n');return out;}
async function safeOutput(dir){try{const s=await fs.lstat(dir);if(s.isSymbolicLink())throw new Error('Symlink output refused');let owned;try{owned=JSON.parse(await fs.readFile(path.join(dir,'.build-manifest.json'),'utf8'));}catch{throw new Error('Unowned output: missing manifest');}if(!Array.isArray(owned))throw new Error('Invalid output manifest');const walk=async(p)=>{for(const e of await fs.readdir(p,{withFileTypes:true})){if(e.isSymbolicLink())throw new Error('Symlink output');const f=path.join(p,e.name),rel=path.relative(dir,f).split(path.sep).join('/');if(e.isDirectory())await walk(f);else if(rel!=='.build-manifest.json'&&!owned.includes(rel))throw new Error('Unowned output '+rel);}};await walk(dir);}catch(e){if(e.code!=='ENOENT')throw e;}}
export async function build({domain=false,output=path.join(root,domain?'dist-domain':'dist')}={}){const d=await load(),h=hosting(domain),out=generate(d,h);for(const rel of ['assets/css/style.css','assets/js/app.js'])out.set(rel,await fs.readFile(path.join(root,'site',rel)));for(const im of [d.portrait.image,...d.releases.map(r=>r.cover),...d.videos.map(v=>v.poster)])for(const rel of [im.path,im.small].filter(Boolean)){safePath(rel);const file=path.join(root,'site',rel);if((await fs.lstat(file)).isSymbolicLink())throw new Error('Symlink media refused');out.set(rel,await fs.readFile(file));}
 await safeOutput(output);const stage=output+'.stage-'+process.pid;await fs.mkdir(stage);try{for(const [rel,data] of out){const dest=path.join(stage,rel);await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,data);}await fs.writeFile(path.join(stage,'.build-manifest.json'),JSON.stringify([...out.keys()])+'\n');await fs.rm(output,{recursive:true,force:true});await fs.rename(stage,output);}catch(e){await fs.rm(stage,{recursive:true,force:true});throw e;}return {files:out.size,releases:d.releases.length,videos:d.videos.length,mode:domain?'custom-domain-preview':'github-preview',h};}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))try{console.log('BUILD_OK',JSON.stringify(await build({domain:process.argv.includes('--domain')})));}catch(e){console.error(e.stack);process.exitCode=1;}
