import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
export const root=fileURLToPath(new URL('../',import.meta.url));
export const locales=['en','pt-BR'];
export const prefix=l=>l==='en'?'':'pt-br/';
export const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const clocks=ms=>{const s=Math.round(ms/1000);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');};
export const types={en:{album:'Album',compilation:'Compilation',mixtape:'Mixtape',single:'Single',ep:'EP'},'pt-BR':{album:'Álbum',compilation:'Coletânea',mixtape:'Mixtape',single:'Single',ep:'EP'}};
export const ui={
 en:{music:'Discography',clips:'Music videos',live:'Live',about:'About',contact:'Contact',menu:'Menu',close:'Close',lang:'Language',role:'Rapper · Songwriter · RUADOFLOW',listen:'Listen',spotify:'Listen on Spotify',youtube:'Watch on YouTube',bio:'Read the biography',albums:'Albums & collective projects',short:'Singles & EPs',selection:'Selected discography',selectionNote:'Records, collaborations and chapters of a life in music.',featured:'Featured films',allVideos:'More music videos',liveTitle:'On stage. In the moment.',videoNote:'The player loads only after you choose to watch.',watch:'Watch video',release:'Release',credits:'Artist credits',year:'Year',tracks:'Tracks',duration:'Running time',tracklist:'Track listing',serviceTitle:'Listed on Spotify as',noLink:'Listening link to be added',return:'Back to discography',openPage:'Open release page',other:'Português',aboutTitle:'A life told through rap.',booking:'Shows, collaborations & cultural projects',contactNote:'Professional contact through RUADOFLOW.',text:'Text version',source:'Sources',rights:'Artwork and music remain the property of their respective rights holders.',skip:'Skip to content',notfound:'Page not found',soon:'This selection is being prepared.'},
 'pt-BR':{music:'Discografia',clips:'Videoclipes',live:'Ao vivo',about:'Sobre',contact:'Contato',menu:'Menu',close:'Fechar',lang:'Idioma',role:'Rapper · Compositor · RUADOFLOW',listen:'Ouvir',spotify:'Ouvir no Spotify',youtube:'Assistir no YouTube',bio:'Ler a biografia',albums:'Álbuns e projetos coletivos',short:'Singles e EPs',selection:'Discografia selecionada',selectionNote:'Discos, colaborações e capítulos de uma vida na música.',featured:'Clipes em destaque',allVideos:'Mais videoclipes',liveTitle:'No palco. No presente.',videoNote:'O player carrega somente quando você escolhe assistir.',watch:'Assistir ao vídeo',release:'Lançamento',credits:'Artistas creditados',year:'Ano',tracks:'Faixas',duration:'Duração',tracklist:'Lista de faixas',serviceTitle:'Nome no Spotify',noLink:'Link de escuta a adicionar',return:'Voltar à discografia',openPage:'Abrir página do lançamento',other:'English',aboutTitle:'Uma vida contada pelo rap.',booking:'Shows, colaborações e projetos culturais',contactNote:'Contato profissional pela RUADOFLOW.',text:'Versão em texto',source:'Fontes',rights:'As obras e músicas pertencem aos seus respectivos titulares.',skip:'Pular para o conteúdo',notfound:'Página não encontrada',soon:'Esta seleção está sendo preparada.'}
};
export function safePath(rel){if(typeof rel!=='string'||!/^assets\/images\/[a-zA-Z0-9_/-]+\.webp$/.test(rel)||rel.includes('..'))throw new Error('Unsafe image path');return rel;}
export async function load(){const read=async file=>JSON.parse(await fs.readFile(path.join(root,'site/content',file+'.json'),'utf8'));return {artist:await read('artist'),releases:await read('releases'),videos:await read('videos'),portrait:await read('portrait')};}
export function validate(d){
 if(d.artist.name!=='A.X.L.'||d.artist.birthYear!=='1990')throw new Error('Artist identity mismatch');
 const ids=new Set();for(const r of d.releases){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(r.id)||ids.has(r.id))throw new Error('Invalid or duplicate release');ids.add(r.id);if(!types.en[r.type]||!r.title||!Number.isInteger(r.year))throw new Error('Invalid release data');if(r.listen&&!/^https:\/\/(open\.spotify\.com\/album\/[A-Za-z0-9]+|www\.youtube\.com\/watch\?v=[A-Za-z0-9_-]{11})$/.test(r.listen))throw new Error('Unsafe listening URL');for(const t of r.tracks)if(!/^https:\/\/open\.spotify\.com\/track\/[A-Za-z0-9]+$/.test(t.url)||!Number.isFinite(t.durationMs)||t.durationMs<=0)throw new Error('Invalid track');}
 for(const v of d.videos)if(!/^[A-Za-z0-9_-]{11}$/.test(v.id)||!['clip','live'].includes(v.kind))throw new Error('Invalid video');
 for(const im of [d.portrait.image,...d.releases.map(r=>r.cover),...d.videos.map(v=>v.poster)]){safePath(im.path);if(im.small)safePath(im.small);if(!(im.width>0&&im.height>0))throw new Error('No intrinsic dimensions');}
 for(const l of locales)if(!d.artist.intro[l]||d.artist.bio[l].length!==4||Object.keys(ui[l]).join()!==Object.keys(ui.en).join())throw new Error('Translation mismatch');
 if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(d.artist.email))throw new Error('Invalid email');
 return true;
}
export const hosting=domain=>domain?{origin:'https://axl.sssom.com',base:'/'}:{origin:'https://contato675.github.io',base:'/axl-portfolio/'};
